# Dependabot configuration
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7

  - package-ecosystem: "nuget"
    directory: "/Runtime/Packages"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
