/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2024, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// Entities are the base of all objects in the scene. Entities are containers into which components can be attached.
    /// </summary>
    [Serializable]
    public class ArenaEntityJson
    {
        public readonly string object_type = "entity";

        // entity member-fields

        private static readonly string defGeometryString = JsonConvert.SerializeObject(JsonConvert.DeserializeObject(""));
        [JsonProperty(PropertyName = "geometry")]
        [Tooltip("The primitive mesh geometry.")]
        public object Geometry = JsonConvert.DeserializeObject("");
        public bool ShouldSerializeGeometry()
        {
            // Geometry (reference type patched)
            return JsonConvert.SerializeObject(Geometry) != defGeometryString;
        }

        private static readonly string defPanelString = JsonConvert.SerializeObject(JsonConvert.DeserializeObject(""));
        [JsonProperty(PropertyName = "panel")]
        [Tooltip("The rounded UI panel primitive.")]
        public object Panel = JsonConvert.DeserializeObject("");
        public bool ShouldSerializePanel()
        {
            // Panel (reference type patched)
            return JsonConvert.SerializeObject(Panel) != defPanelString;
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
