/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2024, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// These effects are enabled in desktop and XR views.
    /// </summary>
    [Serializable]
    public class ArenaPostProcessingJson
    {
        [JsonIgnore]
        public readonly string attributeName = "post-processing";

        // post-processing member-fields

        private static readonly string defBloomString = JsonConvert.SerializeObject(null);
        [JsonProperty(PropertyName = "bloom")]
        [Tooltip("Use bloom post-processing effect.")]
        public object Bloom = null;
        public bool ShouldSerializeBloom()
        {
            // Bloom (reference type patched)
            return JsonConvert.SerializeObject(Bloom) != defBloomString;
        }

        private static readonly string defSaoString = JsonConvert.SerializeObject(null);
        [JsonProperty(PropertyName = "sao")]
        [Tooltip("Use scalable ambient occlusion (SAO) post-processing effect.")]
        public object Sao = null;
        public bool ShouldSerializeSao()
        {
            // Sao (reference type patched)
            return JsonConvert.SerializeObject(Sao) != defSaoString;
        }

        private static readonly string defSsaoString = JsonConvert.SerializeObject(null);
        [JsonProperty(PropertyName = "ssao")]
        [Tooltip("Use screen space ambient occlusion (SSAO) post-processing effect.")]
        public object Ssao = null;
        public bool ShouldSerializeSsao()
        {
            // Ssao (reference type patched)
            return JsonConvert.SerializeObject(Ssao) != defSsaoString;
        }

        private static readonly string defPixelString = JsonConvert.SerializeObject(null);
        [JsonProperty(PropertyName = "pixel")]
        [Tooltip("Use Pixelation post-processing effect.")]
        public object Pixel = null;
        public bool ShouldSerializePixel()
        {
            // Pixel (reference type patched)
            return JsonConvert.SerializeObject(Pixel) != defPixelString;
        }

        private static readonly string defGlitchString = JsonConvert.SerializeObject(null);
        [JsonProperty(PropertyName = "glitch")]
        [Tooltip("Use Glitch post-processing effect.")]
        public object Glitch = null;
        public bool ShouldSerializeGlitch()
        {
            // Glitch (reference type patched)
            return JsonConvert.SerializeObject(Glitch) != defGlitchString;
        }

        private static readonly string defFxaaString = JsonConvert.SerializeObject(null);
        [JsonProperty(PropertyName = "fxaa")]
        [Tooltip("Use FXAA post-processing effect. You may want to place this last in effects list.")]
        public object Fxaa = null;
        public bool ShouldSerializeFxaa()
        {
            // Fxaa (reference type patched)
            return JsonConvert.SerializeObject(Fxaa) != defFxaaString;
        }

        private static readonly string defSmaaString = JsonConvert.SerializeObject(null);
        [JsonProperty(PropertyName = "smaa")]
        [Tooltip("Use SMAA post-processing effect. You may want to place this last in effects list.")]
        public object Smaa = null;
        public bool ShouldSerializeSmaa()
        {
            // Smaa (reference type patched)
            return JsonConvert.SerializeObject(Smaa) != defSmaaString;
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
