/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2023, Carnegie Mellon University. All rights reserved.
 */

using System.Collections.Generic;
using System.Reflection;
using ArenaUnity.Schemas;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace ArenaUnity.Components
{
    public class ArenaModelUpdate : ArenaComponent
    {
        // ARENA modelUpdate component unity conversion status:
        // DONE: looping through every named element for position and rotation

        public ArenaModelUpdateJson json = new ArenaModelUpdateJson();

        private bool modelApplied = false;

        protected override void ApplyRender()
        {
            modelApplied = false;
        }

        private new void Update()
        {
            if (!modelApplied)
            {
                var gltfModel = GetComponent<ArenaWireGltfModel>();
                if (gltfModel == null || gltfModel.isLoaded)
                {
                    ApplyModelUpdates();
                    modelApplied = true;
                }
            }
        }

        private void ApplyModelUpdates()
        {
            if (json == null) return;
            
            // Extract the dynamic bone/node data from the autogenerated json class
            var fieldInfo = typeof(ArenaModelUpdateJson).GetField("_additionalData", BindingFlags.NonPublic | BindingFlags.Instance);
            if (fieldInfo == null) return;

            var additionalData = fieldInfo.GetValue(json) as IDictionary<string, JToken>;
            if (additionalData == null) return;

            // Cache transforms to avoid searching the entire hierarchy repeatedly
            var allTransforms = GetComponentsInChildren<Transform>(true);
            Dictionary<string, Transform> transformDict = new Dictionary<string, Transform>();
            foreach (var t in allTransforms)
            {
                // Cache exact name
                if (!transformDict.ContainsKey(t.name))
                    transformDict.Add(t.name, t);
                    
                // Cache normalized name (A-Frame strips colons and some spaces from bone names)
                string normalizedName = t.name.Replace(":", "").Replace(" ", "");
                if (!transformDict.ContainsKey(normalizedName))
                    transformDict.Add(normalizedName, t);
            }

            foreach (var kvp in additionalData)
            {
                string nodeName = kvp.Key;
                string searchName = nodeName.Replace(":", "").Replace(" ", "");

                if (transformDict.TryGetValue(nodeName, out Transform target) || 
                    transformDict.TryGetValue(searchName, out target))
                {
                    var nodeData = kvp.Value;
                    if (nodeData["position"] != null)
                    {
                        ArenaVector3Json pos = nodeData["position"].ToObject<ArenaVector3Json>();
                        if (pos != null)
                        {
                            target.localPosition = ArenaUnity.ToUnityPosition(pos);
                        }
                    }
                    if (nodeData["rotation"] != null)
                    {
                        ArenaRotationJson rot = nodeData["rotation"].ToObject<ArenaRotationJson>();
                        if (rot != null)
                        {
                            Quaternion unityQuat = ArenaUnity.ToUnityRotationQuat(rot);
                            target.localRotation = ArenaUnity.GltfToUnityRotationQuat(unityQuat);
                        }
                    }
                }
                else
                {
                    Debug.LogWarning($"modelUpdate: Could not find node '{nodeName}' in GLTF hierarchy.");
                }
            }
        }

        public override void UpdateObject()
        {
            PublishIfChanged(json.attributeName, JsonConvert.SerializeObject(json));
        }
    }
}
