/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2023, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// The sound component defines the entity as a source of sound or audio. The sound component is positional and is thus affected by the component's position. More properties at <a href='https://aframe.io/docs/1.4.0/components/sound.html'>https://aframe.io/docs/1.4.0/components/sound.html</a>
    /// </summary>
    [Serializable]
    public class ArenaSoundJson
    {
        public const string componentName = "sound";

        // sound member-fields

        private static bool defAutoplay = false;
        [JsonProperty(PropertyName = "autoplay")]
        [Tooltip("Whether to automatically play sound once set.")]
        public bool Autoplay = defAutoplay;
        public bool ShouldSerializeAutoplay()
        {
            // autoplay
            return (Autoplay != defAutoplay);
        }

        public enum DistanceModelType
        {
            [EnumMember(Value = "linear")]
            Linear,
            [EnumMember(Value = "inverse")]
            Inverse,
            [EnumMember(Value = "exponential")]
            Exponential,
        }
        private static DistanceModelType defDistanceModel = DistanceModelType.Inverse;
        [JsonConverter(typeof(StringEnumConverter))]
        [JsonProperty(PropertyName = "distanceModel")]
        [Tooltip("Sound model: linear, inverse, or exponential.")]
        public DistanceModelType DistanceModel = defDistanceModel;
        public bool ShouldSerializeDistanceModel()
        {
            // distanceModel
            return (DistanceModel != defDistanceModel);
        }

        private static bool defLoop = false;
        [JsonProperty(PropertyName = "loop")]
        [Tooltip("Whether to loop the sound once the sound finishes playing.")]
        public bool Loop = defLoop;
        public bool ShouldSerializeLoop()
        {
            // loop
            return (Loop != defLoop);
        }

        private static float defMaxDistance = 10000f;
        [JsonProperty(PropertyName = "maxDistance")]
        [Tooltip("Maximum distance between the audio source and the listener, after which the volume is not reduced any further.")]
        public float MaxDistance = defMaxDistance;
        public bool ShouldSerializeMaxDistance()
        {
            // maxDistance
            return (MaxDistance != defMaxDistance);
        }

        public enum OnType
        {
            [EnumMember(Value = "mousedown")]
            Mousedown,
            [EnumMember(Value = "mouseup")]
            Mouseup,
            [EnumMember(Value = "mouseenter")]
            Mouseenter,
            [EnumMember(Value = "mouseleave")]
            Mouseleave,
            [EnumMember(Value = "triggerdown")]
            Triggerdown,
            [EnumMember(Value = "triggerup")]
            Triggerup,
            [EnumMember(Value = "gripdown")]
            Gripdown,
            [EnumMember(Value = "gripup")]
            Gripup,
            [EnumMember(Value = "menudown")]
            Menudown,
            [EnumMember(Value = "menuup")]
            Menuup,
            [EnumMember(Value = "systemdown")]
            Systemdown,
            [EnumMember(Value = "systemup")]
            Systemup,
            [EnumMember(Value = "trackpaddown")]
            Trackpaddown,
            [EnumMember(Value = "trackpadup")]
            Trackpadup,
        }
        private static OnType defOn = OnType.Mousedown;
        [JsonConverter(typeof(StringEnumConverter))]
        [JsonProperty(PropertyName = "on")]
        [Tooltip("An event for the entity to listen to before playing sound.")]
        public OnType On = defOn;
        public bool ShouldSerializeOn()
        {
            // on
            return (On != defOn);
        }

        private static float defPoolSize = 1f;
        [JsonProperty(PropertyName = "poolSize")]
        [Tooltip("Numbers of simultaneous instances of this sound that can be playing at the same time")]
        public float PoolSize = defPoolSize;
        public bool ShouldSerializePoolSize()
        {
            // poolSize
            return (PoolSize != defPoolSize);
        }

        private static bool defPositional = true;
        [JsonProperty(PropertyName = "positional")]
        [Tooltip("Whether or not the audio is positional (movable).")]
        public bool Positional = defPositional;
        public bool ShouldSerializePositional()
        {
            // positional
            return (Positional != defPositional);
        }

        private static float defRefDistance = 1f;
        [JsonProperty(PropertyName = "refDistance")]
        [Tooltip("Reference distance for reducing volume as the audio source moves further from the listener.")]
        public float RefDistance = defRefDistance;
        public bool ShouldSerializeRefDistance()
        {
            // refDistance
            return (RefDistance != defRefDistance);
        }

        private static float defRolloffFactor = 1f;
        [JsonProperty(PropertyName = "rolloffFactor")]
        [Tooltip("Describes how quickly the volume is reduced as the source moves away from the listener.")]
        public float RolloffFactor = defRolloffFactor;
        public bool ShouldSerializeRolloffFactor()
        {
            // rolloffFactor
            return (RolloffFactor != defRolloffFactor);
        }

        private static string defSrc = "";
        [JsonProperty(PropertyName = "src")]
        [Tooltip("URL path to sound file e.g. 'store/users/wiselab/sound/wave.mp3'")]
        public string Src = defSrc;
        public bool ShouldSerializeSrc()
        {
            // src
            return (Src != defSrc);
        }

        private static float defVolume = 1f;
        [JsonProperty(PropertyName = "volume")]
        [Tooltip("How loud to play the sound")]
        public float Volume = defVolume;
        public bool ShouldSerializeVolume()
        {
            // volume
            return (Volume != defVolume);
        }

        // General json object management

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;

        public string SaveToString()
        {
            return Regex.Unescape(JsonConvert.SerializeObject(this));
        }

        public static ArenaSoundJson CreateFromJSON(string jsonString, JToken token)
        {
            ArenaSoundJson json = null;
            try {
                json = JsonConvert.DeserializeObject<ArenaSoundJson>(Regex.Unescape(jsonString));
            } catch (JsonReaderException e)
            {
                Debug.LogWarning($"{e.Message}: {jsonString}");
            }
            return json;
        }
    }
}
