/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2023, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// Apply a jitsi video source to the geometry
    /// </summary>
    [Serializable]
    public class ArenaJitsiVideoJson
    {
        [JsonIgnore]
        public readonly string componentName = "jitsi-video";

        // jitsi-video member-fields

        private static string defJitsiId = "";
        [JsonProperty(PropertyName = "jitsiId")]
        [Tooltip("JitsiId of the video source; If defined will override displayName")]
        public string JitsiId = defJitsiId;
        public bool ShouldSerializeJitsiId()
        {
            // jitsiId
            return (JitsiId != defJitsiId);
        }

        private static string defDisplayName = "";
        [JsonProperty(PropertyName = "displayName")]
        [Tooltip("ARENA or Jitsi display name of the video source; Will be ignored if jitsiId is given. (* change requires reload* ) ")]
        public string DisplayName = defDisplayName;
        public bool ShouldSerializeDisplayName()
        {
            return true; // required in json schema
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
