/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2024, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// Overrides absolute size for a 3D model. The model can be a glTF, glb, obj, or any other supported format. The model will be rescaled to fit to the sizes specified for each axes.
    /// </summary>
    [Serializable]
    public class ArenaModelContainerJson
    {
        [JsonIgnore]
        public readonly string componentName = "model-container";

        // model-container member-fields

        private static float defX = 1f;
        [JsonProperty(PropertyName = "x")]
        [Tooltip("Size of the model in the x-axis.")]
        public float X = defX;
        public bool ShouldSerializeX()
        {
            return true; // required in json schema
        }

        private static float defY = 1f;
        [JsonProperty(PropertyName = "y")]
        [Tooltip("Size of the model in the y-axis.")]
        public float Y = defY;
        public bool ShouldSerializeY()
        {
            return true; // required in json schema
        }

        private static float defZ = 1f;
        [JsonProperty(PropertyName = "z")]
        [Tooltip("Size of the model in the z-axis.")]
        public float Z = defZ;
        public bool ShouldSerializeZ()
        {
            return true; // required in json schema
        }

        private static bool defUniform = true;
        [JsonProperty(PropertyName = "uniform")]
        [Tooltip("Whether to scale the model uniformly.")]
        public bool Uniform = defUniform;
        public bool ShouldSerializeUniform()
        {
            return true; // required in json schema
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
