/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2023, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// Generate an event message for an object.
    /// </summary>
    [Serializable]
    public class ArenaEventJson
    {
        public const string componentName = "event";

        // event member-fields

        private static string defSource = "";
        [JsonProperty(PropertyName = "source")]
        [Tooltip("The `object_id` of event origination. e.g camera or client program connection id.")]
        public string Source = defSource;
        public bool ShouldSerializeSource()
        {
            return true; // required in json schema 
        }

        private static object defPosition = JsonConvert.DeserializeObject("{'x': 0, 'y': 0, 'z': 0}");
        [JsonProperty(PropertyName = "position")]
        [Tooltip("The event destination position in 3D.")]
        public object Position = defPosition;
        public bool ShouldSerializePosition()
        {
            return true; // required in json schema 
        }

        private static object defClickPos = JsonConvert.DeserializeObject("{'x': 0, 'y': 1.6, 'z': 0}");
        [JsonProperty(PropertyName = "clickPos")]
        [Tooltip("vector3")]
        public object ClickPos = defClickPos;
        public bool ShouldSerializeClickPos()
        {
            if (_token != null && _token.SelectToken("clickPos") != null) return true;
            return (ClickPos != defClickPos);
        }

        // General json object management

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;

        private static JToken _token;

        public string SaveToString()
        {
            return Regex.Unescape(JsonConvert.SerializeObject(this));
        }

        public static ArenaEventJson CreateFromJSON(string jsonString, JToken token)
        {
            _token = token; // save updated wire json
            ArenaEventJson json = null;
            try {
                json = JsonConvert.DeserializeObject<ArenaEventJson>(Regex.Unescape(jsonString));
            } catch (JsonReaderException e)
            {
                Debug.LogWarning($"{e.Message}: {jsonString}");
            }
            return json;
        }
    }
}
