/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2024, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// The shadow component enables shadows for an entity and its children. Adding the shadow component alone is not enough to display shadows in your scene. We must have at least one light with castShadow: true enabled.
    /// </summary>
    [Serializable]
    public class ArenaShadowJson
    {
        [JsonIgnore]
        public readonly string componentName = "shadow";

        // shadow member-fields

        private static bool defCast = false;
        [JsonProperty(PropertyName = "cast")]
        [Tooltip("Whether the entity casts shadows onto the surrounding scene.")]
        public bool Cast = defCast;
        public bool ShouldSerializeCast()
        {
            return true; // required in json schema
        }

        private static bool defReceive = false;
        [JsonProperty(PropertyName = "receive")]
        [Tooltip("Whether the entity receives shadows from the surrounding scene.")]
        public bool Receive = defReceive;
        public bool ShouldSerializeReceive()
        {
            return true; // required in json schema
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
