/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2023, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// Videosphere Geometry
    /// </summary>
    [Serializable]
    public class ArenaVideosphereJson
    {
        public readonly string object_type = "videosphere";

        // videosphere member-fields

        private static bool defAutoplay = true;
        [JsonProperty(PropertyName = "autoplay")]
        [Tooltip("autoplay")]
        public bool Autoplay = defAutoplay;
        public bool ShouldSerializeAutoplay()
        {
            // autoplay
            return (Autoplay != defAutoplay);
        }

        private static string defCrossOrigin = "anonymous";
        [JsonProperty(PropertyName = "crossOrigin")]
        [Tooltip("crossOrigin")]
        public string CrossOrigin = defCrossOrigin;
        public bool ShouldSerializeCrossOrigin()
        {
            // crossOrigin
            return (CrossOrigin != defCrossOrigin);
        }

        private static bool defLoop = true;
        [JsonProperty(PropertyName = "loop")]
        [Tooltip("loop")]
        public bool Loop = defLoop;
        public bool ShouldSerializeLoop()
        {
            // loop
            return (Loop != defLoop);
        }

        private static float defRadius = 5000f;
        [JsonProperty(PropertyName = "radius")]
        [Tooltip("radius")]
        public float Radius = defRadius;
        public bool ShouldSerializeRadius()
        {
            // radius
            return (Radius != defRadius);
        }

        private static int defSegmentsHeight = 64;
        [JsonProperty(PropertyName = "segmentsHeight")]
        [Tooltip("segments height")]
        public int SegmentsHeight = defSegmentsHeight;
        public bool ShouldSerializeSegmentsHeight()
        {
            // segmentsHeight
            return (SegmentsHeight != defSegmentsHeight);
        }

        private static int defSegmentsWidth = 64;
        [JsonProperty(PropertyName = "segmentsWidth")]
        [Tooltip("segments width")]
        public int SegmentsWidth = defSegmentsWidth;
        public bool ShouldSerializeSegmentsWidth()
        {
            // segmentsWidth
            return (SegmentsWidth != defSegmentsWidth);
        }

        private static string defSrc = "";
        [JsonProperty(PropertyName = "src")]
        [Tooltip("URI, relative or full path of an image/video file. e.g. 'store/users/wiselab/images/360falls.mp4'")]
        public string Src = defSrc;
        public bool ShouldSerializeSrc()
        {
            // src
            return (Src != defSrc);
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
