/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2024, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// Opens an HTML prompt when clicked. Sends text input as an event on MQTT. Requires `click-listener` attribute.
    /// </summary>
    [Serializable]
    public class ArenaTextinputJson
    {
        [JsonIgnore]
        public readonly string componentName = "textinput";

        // textinput member-fields

        public enum OnType
        {
            [EnumMember(Value = "mousedown")]
            Mousedown,
            [EnumMember(Value = "mouseup")]
            Mouseup,
            [EnumMember(Value = "mouseenter")]
            Mouseenter,
            [EnumMember(Value = "mouseleave")]
            Mouseleave,
            [EnumMember(Value = "triggerdown")]
            Triggerdown,
            [EnumMember(Value = "triggerup")]
            Triggerup,
            [EnumMember(Value = "gripdown")]
            Gripdown,
            [EnumMember(Value = "gripup")]
            Gripup,
            [EnumMember(Value = "menudown")]
            Menudown,
            [EnumMember(Value = "menuup")]
            Menuup,
            [EnumMember(Value = "systemdown")]
            Systemdown,
            [EnumMember(Value = "systemup")]
            Systemup,
            [EnumMember(Value = "trackpaddown")]
            Trackpaddown,
            [EnumMember(Value = "trackpadup")]
            Trackpadup,
        }
        private static OnType defOn = OnType.Mousedown;
        [JsonConverter(typeof(StringEnumConverter))]
        [JsonProperty(PropertyName = "on")]
        [Tooltip("A case-sensitive string representing the event type to listen for. See <a href='https://developer.mozilla.org/en-US/docs/Web/Events'>Web Events</a>")]
        public OnType On = defOn;
        public bool ShouldSerializeOn()
        {
            return true; // required in json schema
        }

        private static string defTitle = "";
        [JsonProperty(PropertyName = "title")]
        [Tooltip("The prompt title (optional).")]
        public string Title = defTitle;
        public bool ShouldSerializeTitle()
        {
            return true; // required in json schema
        }

        private static string defLabel = "";
        [JsonProperty(PropertyName = "label")]
        [Tooltip("Label for input (max 140 characters, optional).")]
        public string Label = defLabel;
        public bool ShouldSerializeLabel()
        {
            // label
            return (Label != defLabel);
        }

        private static string defPlaceholder = "";
        [JsonProperty(PropertyName = "placeholder")]
        [Tooltip("Text input placeholder (optional).")]
        public string Placeholder = defPlaceholder;
        public bool ShouldSerializePlaceholder()
        {
            // placeholder
            return (Placeholder != defPlaceholder);
        }

        public enum InputTypeType
        {
            [EnumMember(Value = "text")]
            Text,
            [EnumMember(Value = "email")]
            Email,
            [EnumMember(Value = "password")]
            Password,
            [EnumMember(Value = "number")]
            Number,
            [EnumMember(Value = "tel")]
            Tel,
            [EnumMember(Value = "range")]
            Range,
            [EnumMember(Value = "textarea")]
            Textarea,
            [EnumMember(Value = "url")]
            Url,
            [EnumMember(Value = "select")]
            Select,
            [EnumMember(Value = "radio")]
            Radio,
            [EnumMember(Value = "checkbox")]
            Checkbox,
            [EnumMember(Value = "date")]
            Date,
            [EnumMember(Value = "datetime-local")]
            DatetimeLocal,
            [EnumMember(Value = "time")]
            Time,
            [EnumMember(Value = "week")]
            Week,
            [EnumMember(Value = "month")]
            Month,
        }
        private static InputTypeType defInputType = InputTypeType.Text;
        [JsonConverter(typeof(StringEnumConverter))]
        [JsonProperty(PropertyName = "inputType")]
        [Tooltip("Type of HTML form input")]
        public InputTypeType InputType = defInputType;
        public bool ShouldSerializeInputType()
        {
            // inputType
            return (InputType != defInputType);
        }

        private static string defInputValue = "";
        [JsonProperty(PropertyName = "inputValue")]
        [Tooltip("Input field initial value. Select type will be selected value, for checkbox will be checked state")]
        public string InputValue = defInputValue;
        public bool ShouldSerializeInputValue()
        {
            // inputValue
            return (InputValue != defInputValue);
        }

        private static string[] defInputOptions = {  };
        [JsonProperty(PropertyName = "inputOptions")]
        [Tooltip("Array of options for select or radio input types")]
        public string[] InputOptions = defInputOptions;
        public bool ShouldSerializeInputOptions()
        {
            // inputOptions
            return (InputOptions != defInputOptions);
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
