/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2024, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// Generate an event message for an object.
    /// </summary>
    [Serializable]
    public class ArenaEventJson
    {
        [JsonIgnore]
        public readonly string componentName = "event";

        // event member-fields

        private static string defTarget = null;
        [JsonProperty(PropertyName = "target")]
        [Tooltip("The `object_id` of event destination.")]
        public string Target = defTarget;
        public bool ShouldSerializeTarget()
        {
            return true; // required in json schema
        }

        private static ArenaVector3Json defTargetPosition = null;
        [JsonProperty(PropertyName = "targetPosition")]
        [Tooltip("The event destination position in 3D.")]
        public ArenaVector3Json TargetPosition = defTargetPosition;
        public bool ShouldSerializeTargetPosition()
        {
            return true; // required in json schema
        }

        private static ArenaVector3Json defOriginPosition = JsonConvert.DeserializeObject<ArenaVector3Json>("{'x': 0, 'y': 1.6, 'z': 0}");
        [JsonProperty(PropertyName = "originPosition")]
        [Tooltip("The event origination position in 3D.")]
        public ArenaVector3Json OriginPosition = defOriginPosition;
        public bool ShouldSerializeOriginPosition()
        {
            // originPosition
            return (OriginPosition != defOriginPosition);
        }

        private static string defSource = null;
        [JsonProperty(PropertyName = "source")]
        [Obsolete("DEPRECATED: data.source is deprecated for clientEvent, use data.target instead.")]
        public string Source { get; protected set; } = defSource;
        public bool ShouldSerializeSource()
        {
            return false; // deprecated in json schema
        }

        private static object defPosition = null;
        [JsonProperty(PropertyName = "position")]
        [Obsolete("DEPRECATED: data.position is deprecated for clientEvent, use data.targetPosition instead.")]
        public object Position { get; protected set; } = defPosition;
        public bool ShouldSerializePosition()
        {
            return false; // deprecated in json schema
        }

        private static object defClickPos = null;
        [JsonProperty(PropertyName = "clickPos")]
        [Obsolete("DEPRECATED: data.clickPos is deprecated for clientEvent, use data.originPosition instead.")]
        public object ClickPos { get; protected set; } = defClickPos;
        public bool ShouldSerializeClickPos()
        {
            return false; // deprecated in json schema
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
