/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2024, Carnegie Mellon University. All rights reserved.
 */

// CAUTION: This file is autogenerated from https://github.com/arenaxr/arena-schemas. Changes made here may be overwritten.

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using UnityEngine;

namespace ArenaUnity.Schemas
{
    /// <summary>
    /// A list of available animations can usually be found by inspecting the model file or its documentation. All animations will play by default. To play only a specific set of animations, use wildcards: animation-mixer='clip: run_*'. Requires `object_type: gltf-model`. More properties at <a href='https://github.com/n5ro/aframe-extras/tree/master/src/loaders#animation'>A-Frame Extras Animation</a>.
    /// </summary>
    [Serializable]
    public class ArenaAnimationMixerJson
    {
        [JsonIgnore]
        public readonly string componentName = "animation-mixer";

        // animation-mixer member-fields

        private static bool defClampWhenFinished = false;
        [JsonProperty(PropertyName = "clampWhenFinished")]
        [Tooltip("If true, halts the animation at the last frame.")]
        public bool ClampWhenFinished = defClampWhenFinished;
        public bool ShouldSerializeClampWhenFinished()
        {
            // clampWhenFinished
            return (ClampWhenFinished != defClampWhenFinished);
        }

        private static string defClip = "*";
        [JsonProperty(PropertyName = "clip")]
        [Tooltip("Name of the animation clip(s) to play. Accepts wildcards.")]
        public string Clip = defClip;
        public bool ShouldSerializeClip()
        {
            return true; // required in json schema
        }

        private static float defCrossFadeDuration = 0f;
        [JsonProperty(PropertyName = "crossFadeDuration")]
        [Tooltip("Duration of cross-fades between clips, in seconds.")]
        public float CrossFadeDuration = defCrossFadeDuration;
        public bool ShouldSerializeCrossFadeDuration()
        {
            // crossFadeDuration
            return (CrossFadeDuration != defCrossFadeDuration);
        }

        private static float defDuration = 0f;
        [JsonProperty(PropertyName = "duration")]
        [Tooltip("Duration of the animation, in seconds (0 = auto).")]
        public float Duration = defDuration;
        public bool ShouldSerializeDuration()
        {
            // duration
            return (Duration != defDuration);
        }

        public enum LoopType
        {
            [EnumMember(Value = "once")]
            Once,
            [EnumMember(Value = "repeat")]
            Repeat,
            [EnumMember(Value = "pingpong")]
            Pingpong,
        }
        private static LoopType defLoop = LoopType.Repeat;
        [JsonConverter(typeof(StringEnumConverter))]
        [JsonProperty(PropertyName = "loop")]
        [Tooltip("In repeat and pingpong modes, the clip plays once plus the specified number of repetitions. For pingpong, every second clip plays in reverse.")]
        public LoopType Loop = defLoop;
        public bool ShouldSerializeLoop()
        {
            // loop
            return (Loop != defLoop);
        }

        private static string defRepetitions = "";
        [JsonProperty(PropertyName = "repetitions")]
        [Tooltip("Number of times to play the clip, in addition to the first play (empty string = Infinity). Repetitions are ignored for loop: once.")]
        public string Repetitions = defRepetitions;
        public bool ShouldSerializeRepetitions()
        {
            // repetitions
            return (Repetitions != defRepetitions);
        }

        private static float defStartAt = 0f;
        [JsonProperty(PropertyName = "startAt")]
        [Tooltip("Sets the start of an animation to a specific time (in milliseconds). This is useful when you need to jump to an exact time in an animation. The input parameter will be scaled by the mixer's timeScale.")]
        public float StartAt = defStartAt;
        public bool ShouldSerializeStartAt()
        {
            // startAt
            return (StartAt != defStartAt);
        }

        private static float defTimeScale = 1f;
        [JsonProperty(PropertyName = "timeScale")]
        [Tooltip("Scaling factor for playback speed. A value of 0 causes the animation to pause. Negative values cause the animation to play backwards.")]
        public float TimeScale = defTimeScale;
        public bool ShouldSerializeTimeScale()
        {
            // timeScale
            return (TimeScale != defTimeScale);
        }

        // General json object management
        [OnError]
        internal void OnError(StreamingContext context, ErrorContext errorContext)
        {
            Debug.LogWarning($"{errorContext.Error.Message}: {errorContext.OriginalObject}");
            errorContext.Handled = true;
        }

        [JsonExtensionData]
        private IDictionary<string, JToken> _additionalData;
    }
}
