/**
 * Open source software under the terms in /LICENSE
 * Copyright (c) 2021-2024, Carnegie Mellon University. All rights reserved.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using NUnit.Framework;

namespace ArenaUnity.Tests
{
    /// <summary>
    /// The DTOs under Runtime/Schemas are autogenerated from arena-schemas and every one
    /// carries a CAUTION header saying so. That means nobody reads them, which in turn
    /// means generator drift ships unnoticed. These reflection-driven tests assert the
    /// structural conventions the generator is supposed to hold to, across every DTO at
    /// once, so one broken regeneration fails one test rather than none.
    ///
    /// Each rule below was verified to hold across all 91 schema files at the time of
    /// writing; a failure means either the generator changed or a hand edit slipped in.
    /// </summary>
    [TestFixture]
    public class ArenaSchemaContractTests
    {
        /// <summary>Every concrete DTO in the ArenaUnity.Schemas namespace.</summary>
        private static IEnumerable<TestCaseData> SchemaTypes()
        {
            foreach (Type type in DtoTypes())
                yield return new TestCaseData(type).SetName("Dto_" + type.Name);
        }

        private static IEnumerable<Type> DtoTypes()
        {
            return typeof(ArenaUnity.Schemas.ArenaMessageJson).Assembly
                .GetTypes()
                .Where(t => t.IsClass && !t.IsAbstract && !t.IsGenericType)
                .Where(t => t.Namespace != null && t.Namespace.StartsWith("ArenaUnity.Schemas"))
                .Where(t => t.GetConstructor(Type.EmptyTypes) != null)
                .Where(t => JsonPropertyFields(t).Any())
                .OrderBy(t => t.Name);
        }

        private static IEnumerable<FieldInfo> JsonPropertyFields(Type type)
        {
            return type.GetFields(BindingFlags.Public | BindingFlags.Instance)
                .Where(f => f.GetCustomAttribute<JsonPropertyAttribute>() != null);
        }

        private static string JsonName(FieldInfo field)
        {
            JsonPropertyAttribute attr = field.GetCustomAttribute<JsonPropertyAttribute>();
            return string.IsNullOrEmpty(attr.PropertyName) ? field.Name : attr.PropertyName;
        }

        [Test]
        public void DtoDiscovery_FindsAMeaningfulNumberOfSchemaTypes()
        {
            // Guards the reflection query itself: if a namespace rename made DtoTypes()
            // return nothing, every other test here would vacuously pass.
            Assert.That(DtoTypes().Count(), Is.GreaterThan(50),
                "the schema DTO discovery query has stopped finding types");
        }

        /// <summary>
        /// A duplicated [JsonProperty] name inside one type means one of the two members
        /// silently never round trips.
        /// </summary>
        [TestCaseSource(nameof(SchemaTypes))]
        public void Dto_JsonPropertyNamesAreUniqueWithinTheType(Type type)
        {
            var names = JsonPropertyFields(type).Select(JsonName).ToArray();

            Assert.That(names, Is.Unique,
                $"{type.Name} has duplicate [JsonProperty] names: " +
                string.Join(", ", names.GroupBy(n => n).Where(g => g.Count() > 1).Select(g => g.Key)));
        }

        /// <summary>
        /// The generator's elision convention: every wire member has a matching
        /// ShouldSerializeX() so unchanged values stay off the wire. A member without one
        /// is always serialized, which bloats every publish and can overwrite a value the
        /// user never touched.
        /// </summary>
        [TestCaseSource(nameof(SchemaTypes))]
        public void Dto_EveryWireMemberHasAShouldSerializeMethod(Type type)
        {
            var methods = new HashSet<string>(
                type.GetMethods(BindingFlags.Public | BindingFlags.Instance)
                    .Where(m => m.Name.StartsWith("ShouldSerialize") && m.ReturnType == typeof(bool))
                    .Select(m => m.Name),
                StringComparer.OrdinalIgnoreCase);

            foreach (FieldInfo field in JsonPropertyFields(type))
            {
                Assert.That(methods.Contains("ShouldSerialize" + field.Name), Is.True,
                    $"{type.Name}.{field.Name} has no ShouldSerialize{field.Name}()");
            }
        }

        /// <summary>
        /// Every defX backing default must correspond to a real member and its
        /// ShouldSerialize. A defX left behind after its field was renamed is dead code
        /// that makes the elision look implemented when it is not.
        /// </summary>
        [TestCaseSource(nameof(SchemaTypes))]
        public void Dto_EveryDefaultBackingFieldHasAMatchingMember(Type type)
        {
            var members = new HashSet<string>(
                type.GetFields(BindingFlags.Public | BindingFlags.Instance).Select(f => f.Name),
                StringComparer.OrdinalIgnoreCase);
            var methods = new HashSet<string>(
                type.GetMethods(BindingFlags.Public | BindingFlags.Instance).Select(m => m.Name),
                StringComparer.OrdinalIgnoreCase);

            FieldInfo[] defaults = type
                .GetFields(BindingFlags.NonPublic | BindingFlags.Static)
                .Where(f => f.Name.StartsWith("def") && f.Name.Length > 3)
                .ToArray();

            foreach (FieldInfo backing in defaults)
            {
                string bare = backing.Name.Substring(3);
                // Some defaults compare serialized forms and are named defXString.
                string alternate = bare.EndsWith("String") ? bare.Substring(0, bare.Length - 6) : bare;

                bool matched = members.Contains(bare) || members.Contains(alternate) ||
                               methods.Contains("ShouldSerialize" + bare) ||
                               methods.Contains("ShouldSerialize" + alternate);

                Assert.That(matched, Is.True,
                    $"{type.Name}.{backing.Name} does not correspond to any member or ShouldSerialize");
            }
        }

        /// <summary>
        /// The wire-economy contract, stated in the only way that is both meaningful and
        /// true across the whole schema set: a freshly constructed DTO must serialize to
        /// exactly those members whose ShouldSerialize returns true on that fresh
        /// instance - no more, no fewer.
        ///
        /// Sixty-two DTOs deliberately hardcode `return true; // required in json schema`
        /// for at least one member (ArenaProgramJson.ShouldSerializeEnv() among them), so
        /// asserting a flat "{}" would be wrong. Deriving the expectation from the
        /// ShouldSerialize methods instead still catches the failure that matters: a newly
        /// generated member that is emitted without an eliding guard, or a guard that
        /// Newtonsoft is not honouring.
        /// </summary>
        [TestCaseSource(nameof(SchemaTypes))]
        public void Dto_FreshInstanceSerializesExactlyItsRequiredMembers(Type type)
        {
            object instance;
            try
            {
                instance = Activator.CreateInstance(type);
            }
            catch (Exception e)
            {
                Assert.Ignore($"{type.Name} cannot be default-constructed: {e.GetType().Name}");
                return;
            }

            var expected = new SortedSet<string>();
            foreach (FieldInfo field in JsonPropertyFields(type))
            {
                MethodInfo should = type.GetMethod("ShouldSerialize" + field.Name,
                    BindingFlags.Public | BindingFlags.Instance, null, Type.EmptyTypes, null);
                if (should == null || (bool)should.Invoke(instance, null))
                    expected.Add(JsonName(field));
            }

            string json = JsonConvert.SerializeObject(instance);
            JToken token = JToken.Parse(json);

            if (token.Type != JTokenType.Object)
                Assert.Ignore($"{type.Name} has a custom converter that does not emit an object");

            var emitted = new SortedSet<string>(((JObject)token).Properties().Select(p => p.Name));

            Assert.That(emitted, Is.EquivalentTo(expected),
                $"{type.Name} emitted [{string.Join(", ", emitted)}] " +
                $"but its ShouldSerialize methods asked for [{string.Join(", ", expected)}]");
        }

        /// <summary>
        /// Nothing may be emitted that is not a declared wire member. Catches a public
        /// field that lost its [JsonProperty] attribute, which would start publishing an
        /// unexpected key under its C# name.
        /// </summary>
        [TestCaseSource(nameof(SchemaTypes))]
        public void Dto_EmitsNoUndeclaredMembers(Type type)
        {
            object instance;
            try { instance = Activator.CreateInstance(type); }
            catch (Exception e) { Assert.Ignore($"{type.Name} cannot be default-constructed: {e.GetType().Name}"); return; }

            JToken token = JToken.Parse(JsonConvert.SerializeObject(instance));
            if (token.Type != JTokenType.Object)
                Assert.Ignore($"{type.Name} has a custom converter that does not emit an object");

            var declared = new HashSet<string>(JsonPropertyFields(type).Select(JsonName));

            foreach (JProperty property in ((JObject)token).Properties())
            {
                Assert.That(declared.Contains(property.Name), Is.True,
                    $"{type.Name} emitted undeclared member '{property.Name}'");
            }
        }

        // ==================================================== enum wire values

        private static IEnumerable<TestCaseData> SchemaEnums()
        {
            foreach (Type type in typeof(ArenaUnity.Schemas.ArenaMessageJson).Assembly
                         .GetTypes()
                         .Where(t => t.IsEnum)
                         .Where(t => t.Namespace != null && t.Namespace.StartsWith("ArenaUnity.Schemas"))
                         .Where(t => t.GetFields(BindingFlags.Public | BindingFlags.Static)
                                      .Any(f => f.GetCustomAttribute<EnumMemberAttribute>() != null))
                         .OrderBy(t => t.FullName))
            {
                yield return new TestCaseData(type).SetName("Enum_" + type.DeclaringType?.Name + "_" + type.Name);
            }
        }

        [Test]
        public void EnumDiscovery_FindsSchemaEnums()
        {
            Assert.That(SchemaEnums().Count(), Is.GreaterThan(10),
                "the [EnumMember] enum discovery query has stopped finding enums");
        }

        /// <summary>
        /// A duplicated [EnumMember] value means two C# members share one wire string, so
        /// a round trip silently collapses them into whichever comes first.
        /// </summary>
        [TestCaseSource(nameof(SchemaEnums))]
        public void Enum_MemberValuesAreUnique(Type enumType)
        {
            var values = enumType.GetFields(BindingFlags.Public | BindingFlags.Static)
                .Select(f => f.GetCustomAttribute<EnumMemberAttribute>())
                .Where(a => a != null)
                .Select(a => a.Value)
                .ToArray();

            Assert.That(values, Is.Unique, $"{enumType.Name} has duplicate [EnumMember] values");
        }

        /// <summary>
        /// The wire protocol assertion: serializing an enum member through
        /// StringEnumConverter must emit exactly its [EnumMember] value, and reading that
        /// string back must return the same member. A renamed C# member that forgets to
        /// keep its EnumMember value would otherwise change the MQTT payload silently.
        /// </summary>
        [TestCaseSource(nameof(SchemaEnums))]
        public void Enum_EveryMemberRoundTripsThroughItsWireValue(Type enumType)
        {
            var converter = new StringEnumConverter();

            foreach (FieldInfo field in enumType.GetFields(BindingFlags.Public | BindingFlags.Static))
            {
                EnumMemberAttribute attr = field.GetCustomAttribute<EnumMemberAttribute>();
                if (attr == null) continue;

                object member = field.GetValue(null);

                string json = JsonConvert.SerializeObject(member, converter);
                Assert.That(json, Is.EqualTo("\"" + attr.Value + "\""),
                    $"{enumType.Name}.{field.Name} must serialize as '{attr.Value}'");

                object back = JsonConvert.DeserializeObject(json, enumType, converter);
                Assert.That(back, Is.EqualTo(member),
                    $"{enumType.Name}.{field.Name} must deserialize back from '{attr.Value}'");
            }
        }
    }
}
